#Definicion de projectos ligados a una organizacion mediante la tag owner
harness_platform_projects = {
  "Organization Setup" = {
    enable       = true
    description  = "Project generated by terraform harness provider"
    tags         = ["tecnologia: terraform"]
    organization = "Cristian DevSecOps TF"
  }
}
