harness_platform_kubernetes_connectors = {}
harness_platform_helm_connectors = {
  "prometheus-helm" = {
    enable      = true
    description = "Connector generated by terraform harness provider"
    tags        = []
    environment = "pro"
    url         = "https://prometheus-community.github.io/helm-charts"
  }
}
